name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Frontend Docker image
      run: |
        cd hotel-front
        docker build -t hotel-front:$(date +%s) .
    
    - name: Build Backend Docker image
      run: |
        cd hotel-back
        docker build -t hotel-back:$(date +%s) .
