name: Run Playwright Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [10, 12, 14]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    # Primero generamos el package-lock.json
    - name: Generate package-lock.json
      run: npm install --package-lock-only
    # Ahora podemos usar npm ci
    - name: Install dependencies
      run: npm ci
    - run: npx playwright install --with-deps
    - run: npx playwright test
