name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Run tests
      run: |
        docker-compose up -d
        # Comandos de prueba específicos
